---
services:
  jncep-webui:
    image: naruzosa/jncep_webui
    environment:
      - JNCEP_EMAIL=${JNCEP_EMAIL}
      - JNCEP_PASSWORD=${JNCEP_PASSWORD}
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/logs
    restart: unless-stopped